name: cs3dash
channels:
  - dwr-cvm
  - cadwr-dms
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # MSO packages
  # - csrs
  - pandss
  # - calsim_objects
  # Basics
  - pandas
  # Plotting/Dashboard
  - dash
  - dash-bootstrap-components
  - plotly
  - seaborn
  # Misc
  - flake8
  - httpx
  - pyyaml
